### ISSUE TITLE
gg4clj with Hiccup?

### ISSUE THREAD

**Issue by aaelony** [JonyEpsilon/gg4clj#1]
Hi,

This is more of a question than an issue per se.  I have a ring web app that I'd like to explore using with gg4clj.   I have tried

``` clojure
(h/html [:head] [:body 
[:h1 "testing"] 
(gg4clj/view [[:<- :g (gg4clj/data-frame g-dat)]
              (gg4clj/r+
                [:ggplot :g [:aes :g1 :g2]]
                [:xlim -2 2]
                [:ylim -2 2]
                [:geom_point {:colour "steelblue" :size 4}]
                [:stat_density2d {:colour "#FF29D2"}]
                [:theme_bw])]
             {:width 5 :height 5})
] )
```

and get

```
gg4clj.core.GGView@f4e6e6a8
```

rather than the cartoon.

How can I appropriate the canonical example in the readme within Hiccup ?

Thank-you,
Avram

**Comment by JonyEpsilon** [comment]
Hi Avram,

 `gg4clj/view` adds a wrapper specifically for Gorilla REPL's rendered. The function `gg4clj/render` might be more useful as it just generates a string with the SVG code in. I don't know whether it's possible to include a raw string into Hiccup output the way you've done it above, but if it is then `render` will help.

Jony

**Comment by aaelony** [comment]
Thank-you, I will try gg4clj/render and experiment a bit.
Avram
