### ISSUE TITLE
[bug] Empty output

### ISSUE THREAD

**Issue by sbelak** [JonyEpsilon/gg4clj#2]
<img width="985" alt="screenshot 2015-10-15 16 17 15" src="https://cloud.githubusercontent.com/assets/178038/10516363/374554cc-7358-11e5-8986-65ad15f48ccc.png">

OS X 10.9.5
R 3.1.2
Gorilla REPL 0.35
Clojure 1.8 apha-4

plotting with ggplot2 from the R console works fine. 

Dumping to svg produces an empty file. 

WS response:
'''
{"id":"29fe0b3f-7c54-4733-a507-b6c57e254418","ns":"gg4clj.demo","session":"4296a6e5-3b03-4c6c-b004-a294f39a27cc","value":"\"{\\"type\\":\\"html\\",\\"content\\":\\"\\",\\"value\\":\\"#gg4clj.core.GGView{:plot-command [:qplot :mpg :hp {:data :mtcars, :color [:factor :cyl]}], :options {}}\\"}\""}
'''

**Comment by sbelak** [comment]
Solved it. The problem was with the version of R that brew installed. Updating brew, then r, then reinstalling ggplot2 solved it.

**Comment by JonyEpsilon** [comment]
Huh, that's weird. Thanks for reporting and following up with the solution :-)
